name: wasm_bindings_gen
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-257.0.dev

# Add regular dependencies here.
dependencies:
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  path: ^1.9.0
  wasmi:
    path: ../wasmi

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
